/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e2e2e2",
        "primary-fixed": "#e2e2e2",
        "on-error-container": "#93000a",
        "background-col": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#464747",
        "primary-container": "#1b1b1b",
        "surface-tint": "#5e5e5e",
        "secondary-fixed": "#e4e2e2",
        "on-primary-fixed-variant": "#474747",
        "tertiary-fixed": "#e2e2e2",
        "on-primary-container": "#848484",
        "on-tertiary-fixed-variant": "#474747",
        "border-strong": "#000000",
        "dark-border-subtle": "#262626",
        "on-surface-variant": "#4c4546",
        "dark-text-main": "#FFFFFF",
        "bg-secondary": "#F9F9F9",
        "text-main": "#111111",
        "inverse-surface": "#2f3131",
        "dark-bg-secondary": "#1A1A1A",
        "border-subtle": "#E5E5E5",
        "surface-container-low": "#f3f3f3",
        "on-secondary-fixed": "#1b1c1c",
        "on-primary": "#ffffff",
        "ds-tertiary": "#000000",
        "dark-text-muted": "#A3A3A3",
        "tertiary-container": "#1b1b1b",
        "error-container": "#ffdad6",
        "text-muted": "#6B7280",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "bg-primary": "#FFFFFF",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#c6c6c6",
        "secondary-fixed-dim": "#c7c6c6",
        "dark-bg-primary": "#0A0A0A",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed": "#1b1b1b",
        "outline": "#7e7576",
        "surface-container-highest": "#e2e2e2",
        "outline-variant": "#cfc4c5",
        "on-tertiary-container": "#848484",
        "on-primary-fixed": "#1b1b1b",
        "on-secondary-container": "#626262",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        "ds-error": "#ba1a1a",
        "surface-container-high": "#e8e8e8",
        "inverse-on-surface": "#f1f1f1",
        "secondary": "#5e5e5e",
        "surface-container": "#eeeeee",
        "surface": "#f9f9f9",
        "secondary-container": "#e1dfdf",
        "ds-primary": "#000000",
      },
      maxWidth: {
        "content-width": "680px",
      },
      spacing: {
        "stack-gap": "1.5rem",
        "container-padding-mobile": "1.25rem",
        "section-gap": "4rem",
        "inline-gap": "0.75rem",
        "container-padding-desktop": "2rem",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
